services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus:v3.1.0
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=1y'
            - '--web.enable-lifecycle'
        ports:
            - "9090:9090"
        restart: on-failure
    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter-linux-armv7
        ports:
            - "9100:9100"
        restart: on-failure
    json-exporter:
        container_name: json-exporter
        image: prometheuscommunity/json-exporter:v0.6.0
        volumes:
            - ./json-exporter.yml:/config.yml
        ports:
            - "7979:7979"
        restart: on-failure
volumes:
    prometheus_data: {}
    dhparam_cache: {}