global:
  scrape_interval: 5s
  external_labels:
    monitor: 'idkwhatimdoing'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'json-exporter'
    static_configs:
      - targets: ['json-exporter:7979']
  - job_name: 'airquality'
    static_configs:
      - targets:
        - http://ag-bedrooms.cincoptimo.com/metrics
        - http://ag-living.cincoptimo.com/metrics
        - http://ag-office.cincoptimo.com/metrics
        - http://ag-outside.cincoptimo.com/metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: 'http://(.*)\.cincoptimo\.com.*'
        target_label: instance
        replacement: '$1'
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: json-exporter:7979
